<a href="https://colab.research.google.com/github/Induvardhan116/P-S-Lab/blob/main/P_S_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
a = [2,4,34,85,7,32,24,90]
arr = np.array(a)
print(arr)

[ 2  4 34 85  7 32 24 90]


In [8]:
arr = np.array(a)
arr = np.array([2,4,34,85,7,32,24,90])
print(arr)

[ 2  4 34 85  7 32 24 90]


In [9]:
print(arr[3])
print(arr[6])

85
24


In [10]:
aa=[[1,4,2,7],[3,9,6,0]]
A=np.array(aa)
print(A)

[[1 4 2 7]
 [3 9 6 0]]


In [11]:
A=np.array([[1,4,2,7],[3,9,6,0]])
print(A)


[[1 4 2 7]
 [3 9 6 0]]


In [12]:
print(type(A))

<class 'numpy.ndarray'>


In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
np.ndim(arr)

1

In [15]:
np.ndim(A)

2

In [16]:
print(np.size(arr))

8


In [17]:
print(np.size(A))

8


In [18]:
print(np.shape(arr))

(8,)


In [19]:
print(np.shape(A))

(2, 4)


In [20]:
A=np.array([[1,2,5],[6,4,3],[8,0,9]])
print(A)

[[1 2 5]
 [6 4 3]
 [8 0 9]]


In [21]:
print(A[0,:])
print(A[1,:])
print(A[2,:])

[1 2 5]
[6 4 3]
[8 0 9]


In [22]:
print(A[:,0])
print(A[:,1])
print(A[:,2])

[1 6 8]
[2 4 0]
[5 3 9]


In [23]:
print(A[2,2])

9


In [24]:
import pandas as pd

In [25]:
Dataset={
 "State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
 "Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
 "Literacy %": [87, 76, 92, 97,67],
 "Avg High Temp(c)": [45, 24, 15, 44, 32 ]}
print(Dataset)

{'State': ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'], 'Literacy %': [87, 76, 92, 97, 67], 'Avg High Temp(c)': [45, 24, 15, 44, 32]}


In [26]:
df = pd.DataFrame(Dataset)
print(df)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          87                45
1     Maharashtra      Mumbai          76                24
2       Karnataka   Bengaluru          92                15
3          Kerala  Trivandrum          97                44
4      Tamil Nadu     Chennai          67                32


In [27]:
df = pd.DataFrame({
 "State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
 "Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
 "Literacy %": [87, 76, 92, 97,67],
 "Avg High Temp(c)": [45, 24, 15, 44, 32 ]
})
print(df)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          87                45
1     Maharashtra      Mumbai          76                24
2       Karnataka   Bengaluru          92                15
3          Kerala  Trivandrum          97                44
4      Tamil Nadu     Chennai          67                32


In [28]:
print(df.head(2))

            State    Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh  Hyderabad          87                45
1     Maharashtra     Mumbai          76                24


In [29]:
print(df.tail(3))

        State     Capital  Literacy %  Avg High Temp(c)
2   Karnataka   Bengaluru          92                15
3      Kerala  Trivandrum          97                44
4  Tamil Nadu     Chennai          67                32


In [30]:
print(df.dtypes)

State               object
Capital             object
Literacy %           int64
Avg High Temp(c)     int64
dtype: object


In [31]:
print(df.sort_values('Literacy %', ascending=False))

            State     Capital  Literacy %  Avg High Temp(c)
3          Kerala  Trivandrum          97                44
2       Karnataka   Bengaluru          92                15
0  Andhra Pradesh   Hyderabad          87                45
1     Maharashtra      Mumbai          76                24
4      Tamil Nadu     Chennai          67                32


In [32]:
print(df[['Capital']])

      Capital
0   Hyderabad
1      Mumbai
2   Bengaluru
3  Trivandrum
4     Chennai


In [33]:
print(df[['State', 'Capital']])

            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karnataka   Bengaluru
3          Kerala  Trivandrum
4      Tamil Nadu     Chennai


In [34]:
print(df.loc[2])

State               Karnataka
Capital             Bengaluru
Literacy %                 92
Avg High Temp(c)           15
Name: 2, dtype: object


In [35]:
print(df.iloc[2])

State               Karnataka
Capital             Bengaluru
Literacy %                 92
Avg High Temp(c)           15
Name: 2, dtype: object


In [36]:
print(df.iloc[1,2])

76


In [37]:
print(df.loc[1,'Literacy %'])

76


In [38]:
a={"Distance":[15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16,17, 14, 17, 17, 16, 14, 15, 16, 17, 14, 16, 15, 17, 13]}

In [39]:


import pandas as pd
df=pd.DataFrame(a)
print(df)
print('The number of elements in the column is =',df['Distance'].size)

    Distance
0         15
1         13
2         16
3         16
4         15
5         16
6         17
7         14
8         15
9         16
10        16
11        17
12        14
13        17
14        17
15        16
16        14
17        15
18        16
19        17
20        14
21        16
22        15
23        17
24        13
The number of elements in the column is = 25


In [40]:
df2=pd.crosstab(index=df['Distance'],columns='Frequency')
print(df2)

col_0     Frequency
Distance           
13                2
14                4
15                5
16                8
17                6


In [41]:
print(df2['Frequency'].sum())

25


In [42]:
df2['Relative_Frequencies']=df2['Frequency']/df2['Frequency'].sum()
df2['Percentage']=df2['Frequency']/df2['Frequency'].sum()*100
print(df2)

col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
13                2                  0.08         8.0
14                4                  0.16        16.0
15                5                  0.20        20.0
16                8                  0.32        32.0
17                6                  0.24        24.0


In [43]:
df2.loc['Total']=df2.sum()
print(df2)

col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
13              2.0                  0.08         8.0
14              4.0                  0.16        16.0
15              5.0                  0.20        20.0
16              8.0                  0.32        32.0
17              6.0                  0.24        24.0
Total          25.0                  1.00       100.0


In [44]:
import numpy as np
import pandas as pd

In [45]:
data=[328, 470, 405, 375, 298, 326, 276, 362, 410, 255, 391, 370, 455, 229, 300, 183,
 283, 366, 400, 495, 215, 157, 374, 306, 280, 409, 321, 269, 398, 200]
diction={"Score":data}
df=pd.DataFrame(diction)
print(df)

    Score
0     328
1     470
2     405
3     375
4     298
5     326
6     276
7     362
8     410
9     255
10    391
11    370
12    455
13    229
14    300
15    183
16    283
17    366
18    400
19    495
20    215
21    157
22    374
23    306
24    280
25    409
26    321
27    269
28    398
29    200


In [46]:
A=min(data)
print('The lowest value is ',A)
B=max(data)
print('The highestest value is ',B)
N=round((B-A)/50)
N

The lowest value is  157
The highestest value is  495


7

In [47]:
bins=np.linspace(150,500,N+1)
print(bins)

[150. 200. 250. 300. 350. 400. 450. 500.]


In [48]:
df['Class Intervals']=pd.cut(df['Score'],bins=bins,right=False,)
print(df)

    Score Class Intervals
0     328  [300.0, 350.0)
1     470  [450.0, 500.0)
2     405  [400.0, 450.0)
3     375  [350.0, 400.0)
4     298  [250.0, 300.0)
5     326  [300.0, 350.0)
6     276  [250.0, 300.0)
7     362  [350.0, 400.0)
8     410  [400.0, 450.0)
9     255  [250.0, 300.0)
10    391  [350.0, 400.0)
11    370  [350.0, 400.0)
12    455  [450.0, 500.0)
13    229  [200.0, 250.0)
14    300  [300.0, 350.0)
15    183  [150.0, 200.0)
16    283  [250.0, 300.0)
17    366  [350.0, 400.0)
18    400  [400.0, 450.0)
19    495  [450.0, 500.0)
20    215  [200.0, 250.0)
21    157  [150.0, 200.0)
22    374  [350.0, 400.0)
23    306  [300.0, 350.0)
24    280  [250.0, 300.0)
25    409  [400.0, 450.0)
26    321  [300.0, 350.0)
27    269  [250.0, 300.0)
28    398  [350.0, 400.0)
29    200  [200.0, 250.0)


In [49]:
table2=pd.crosstab(index=df['Class Intervals'],columns='Frequency')

In [50]:
table2

col_0            Frequency
Class Intervals           
[150.0, 200.0)           2
[200.0, 250.0)           3
[250.0, 300.0)           6
[300.0, 350.0)           5
[350.0, 400.0)           7
[400.0, 450.0)           4
[450.0, 500.0)           3

In [51]:
import pandas as pd

# Data
data = [328, 470, 405, 375, 298, 326, 276, 362, 410, 255, 391, 370, 455, 229, 300,
        183, 283, 366, 400, 495, 215, 157, 374, 306, 280, 409, 321, 269, 398, 200]

# Define intervals
bin_edges = list(range(150, 501, 50))
interval_labels = [f"{bin_edges[i]}-{bin_edges[i+1]-1}" for i in range(len(bin_edges) - 1)]

# Compute frequency distribution
# Remove the 'sort=False' argument
frequency = pd.cut(data, bins=bin_edges, right=False, labels=interval_labels).value_counts()
# Sort the index if needed
frequency = frequency.sort_index()

# Create the frequency table
frequency_table = pd.DataFrame({
    "Interval": interval_labels,  # Changed to interval_labels
    "Frequency": frequency.values
})

frequency_table

Interval  Frequency
0  150-199          2
1  200-249          3
2  250-299          6
3  300-349          5
4  350-399          7
5  400-449          4
6  450-499          3